### ISSUE TITLE
Add variant of is_shortened: should_resolve

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/ural#107]
Investigate cases like:

https://irefeurope.us7.list-manage.com/subscribe?id=190b7c560e&u=f8bd83cfe3e7706dcaa7b3cce
https://mediatico.us3.list-manage.com/track/click?e=ee25428e59&id=a6cdf43ce1&u=3b55def8ea4fbfec39e9658e5
https://politico.us8.list-manage.com/track/click?e=8c1070a21b&id=36eba34e60&u=e26c1a1c392386a968d02fdbc
https://bvoltaire.us6.list-manage.com/track/click?e=eee24160e6&id=e97c474993&u=51e3861403b406b07f6c5091a
https://bvoltaire.us6.list-manage.com/track/click?e=eee24160e6&id=06f1c1fc78&u=51e3861403b406b07f6c5091a
https://lemouvementassociatif.us11.list-manage.com/
https://fnuja.us14.list-manage.com/track/click?e=7213cd5610&id=087a36fced&u=6f68322b9f6ffeef88d8eef6a
https://euralia.us11.list-manage.com/subscribe?id=bb91768eef&u=f9407aad63da928422682ec92
https://bvoltaire.us6.list-manage.com/track/click?e=eee24160e6&id=19ed619a71&u=51e3861403b406b07f6c5091a
https://lesalonbeige.us2.list-manage.com/track/click?e=eb2ad2e77chttps://www.lesalonbeige.fr/ambiance-surprenante-au-meeting-de-valerie-pecresse/?utm_source=rss&id=a99261d7b6&mc_cid=285da4a42a&u=71b5ff0a93830214b96a42bf6
https://groupe-egae.us2.list-manage.com/track/click?e=58dd713744&id=1877332180&u=c3456bbbde07c441617e0fe02
https://causeur.us5.list-manage.com/track/click?e=92e5d13048&id=87ba7c0263&u=49351cee1aebe6853536334fb
https://ensemblepourleure.us7.list-manage.com/track/click?e=aaa333daf2&id=8e0c9945d8&u=c3a3f1e5edfd960df6a347715
https://telos-eu.us4.list-manage.com/track/click?e=4a41265909&id=12b4c958a9&u=5c33dbbef9d8151a3dd8a5131
https://mateusz.us4.list-manage.com/track/click?e=006ec6e0fa&id=eb695b5f73&u=d5ce8ee799fb411b94fdfedce

https://u23577726.ct.sendgrid.net/ls/click?upn=UoFcOrsBdCuWzBIN4jDCRJKYCjjX59IqE3GzYl3pXVe5kJIfCA7u7yDuHrf7HOCFclA7_LXAcL-2FF8UdDyuXJenWT7edIAbIvV0ig-2Bi-2BTiHoB8xRU4HlsvwdN1gGQyYO1WJGTZtnC77XAXUyVNd-2FcqzWx6ttSuBZ8HuNgUHWrL92aJ4m-2B287goMoy-2BaCgqWli8HnFUPAulRpOXC98Y2rEjCIsaKEtFnm6I2JS5RjRBZMzS-2BwNdLmQRuEql-2B-2BhWtxgMkARUHwZioH8CgLnD29bQf2v-2FHzCWwfXjfDeKmuE2hFK6oA-2B3d1K-2BH119aCMciHm7O391dVFcrsgxPOh6Uj2GK7lgHQ-3D-3D

doi.org

**Comment by boogheta** [comment]
Les list-manage ca vient d'outils de newsletter avec tracker de click

**Comment by Yomguithereal** [comment]
Oui mais du coup ça ressemble au genre de truc que tu veux resolve typiquement, non?

**Comment by Yomguithereal** [comment]
okay
