### ISSUE TITLE
Should is_youtube_url be stricter?

### ISSUE THREAD

**Issue by boogheta** [medialab/ural#119]
Currently is_youtube_url relies on this regexp:
https://github.com/medialab/ural/blob/master/ural/youtube.py#L15

So as long a a domain contains "youtube." is it accounted, although there seems to exist within the twitter urls corpus some false positives, such as youtube.je.

Should we make this stricter?
cc @kat-kel

**Comment by Yomguithereal** [comment]
One thing to keep in mind is that `youtube.fr` and `youtube.co.uk` are actual YouTube redirection domains that do exist. It's rare to find those urls in the wild but it is still possible. So maybe the only good way to do this is trying to find all the real YT redirections domains by scanning the most probable ones to build a white list?

**Comment by boogheta** [comment]
Sounds like the way to go indeed
