### ISSUE TITLE
parser for Facebook URLS does not accurately identify Facebook Groups

### ISSUE THREAD

**Issue by kat-kel** [medialab/ural#124]
The function `parse_facebook_url()` does not accurately identify when a URL points to a Facebook group.

**Comment by Yomguithereal** [comment]
Can you show examples?

**Comment by Yomguithereal** [comment]
Note that in some cases, it is impossible. Hence the `FacebookHandle` parsed result here: https://github.com/medialab/ural/blob/master/ural/facebook.py#L170

**Comment by kat-kel** [comment]
Désolée, j'avais appliqué dans mon code une solution à l'issue que Laura était en train de régler (https://github.com/medialab/ural/pull/117/files#diff-190c4fd74eeecad95f9253d1ea7516b1cbe6f8135f72e692cf9a39b90665ff39), mais ma petite solution n'était pas complète et il a fait que les groupes n'entrent pas dans le reste de la boucle, et donc la fonction `parse_facebook_url()` n'avait pas l'occasion de les traiter. Désolée. C'est pas une issue.
