### ISSUE TITLE
(?un)handle trailing slashes ?

### ISSUE THREAD

**Issue by boogheta** [medialab/ural#3]
Currently normalize_url trashes trailing slashes, although it is not a so uncommon practice that a website would serve two different things at http://www.domain.tld/path/ and http://www.domain.tld/path

So I'm not sure this normalising should remain, or at least maybe it could be optional only, depending on the usage to be done further on (for instance requesting share values on facebook ;) )

**Comment by Yomguithereal** [comment]
This should be an option indeed.

**Comment by boogheta** [comment]
moreover, in our current case, since urls have been resolved, redirections pointed us to the urls with the trailing slash when it is the same, so we really don't want to normalize it here
