### ISSUE TITLE
Notes related to normalize_url enhancements

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/ural#4]
* puny code [done]
* sorting query params [done]
* protocol option
* authentication [done]
* option for trailing / [done]
* case? [done]
* https://en.wikipedia.org/wiki/URL_normalization

**Comment by boogheta** [comment]
- alphabetically order query's arguments?

**Comment by Yomguithereal** [comment]
Already written above :)

**Comment by boogheta** [comment]
pfff indeed my bad, and i screened it twice to check...
