### ISSUE TITLE
normalize_url crashes on some urls

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/ural#62]
* https://www.jungewelt.de/loginFailed.php?ref=/artikel/312583.kampf-gegen-macron-au%C3%9Ferparlamentarisch-f%C3%BChren.html
* http://www.milletpress.com/Detail_EN.aspx?Jiamre=2038&T=%E2%80%8BTurkey%20Plan%20Assassination%20of%20Kurdish%20Activists%20Abroad

**Comment by boogheta** [comment]
FYI, it's urllib that raises KeyErrors on accents such as u'\xc3' u'\xe2' etc
