### ISSUE TITLE
Improve normalize

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/ural#67]
* `/photo.php?fbid=1454919154621936&amp;id=598338556946671&amp;set=a.600335226747004&amp;__ccr=ARalImU2qhrrHFuCIUFpLdb30fXaDuEj2KsKk_ikE_-8ww&amp;__tn__=%2B%3E`

**Comment by boogheta** [comment]
Maybe handle such cases as well ?
https://www.facebook.com/lavraiedemocratie/videos/2443555575953497 -> https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Flavraiedemocratie%2Fvideos%2F2443555575953497
